services:
  - type: web
    name: ruz-flask
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --workers 3 --bind 0.0.0.0:$PORT"
    envVars:
      - key: FLASK_APP
        value: "app.py"
      - key: FLASK_ENV
        value: "production"
      - key: DATABASE_URL
        value: "postgres://your_postgres_url_here"
    regions:
      - oregon
